############################################################
# Licht aus, wenn die Sonne schon scheint
############################################################
- alias: "Sonnenaufgang"
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: switch.turn_off
      entity_id: group.licht
    - service: light.turn_off
      entity_id: group.all_lights
    - service: telegram_bot.send_message
      data_template:
        target: !secret chatid_1
        message: "Die Sonne geht auf, Licht aus."

############################################################
# Random Color loop
############################################################
- alias: 'Partymodus Wohnzimmer'
  trigger:
    platform: time_pattern
    seconds: "/30"
  condition:
    condition: state
    entity_id: input_boolean.livingroom_partymode
    state: 'on'
  action:
    service: light.turn_on
    entity_id: group.wohnzimmer_hue
    data:
      effect: random
      transition: 5

############################################################
# Select Scene for Hue lights
############################################################
- alias: "Hue Szene auswählen"
  trigger:
    platform: state
    entity_id: input_select.light_scenes
  action:
    service: hue.hue_activate_scene
    data_template:
      group_name: "Wohnzimmer"
      scene_name: '{{ states.input_select.light_scenes.state }}'

