############################################################
#                                                          #
# Home Assistant Main Configuration File                   #
#                                                          #
############################################################
homeassistant:
  name:                  FrikaHome
  latitude:              !secret lat
  longitude:           !secret lot
  elevation:           77
  unit_system:      metric
  time_zone:        "Europe/Berlin"
  customize:        !include includes/customize.yaml

http:
  # Uncomment this to add a password (recommended!)
  api_password:          !secret http_password
  #trusted_networks:
  #  - 192.168.0.0/24

updater:
discovery:
conversation:
history:
map:
recorder:
  purge_interval:        14
  purge_keep_days:    13
  exclude:
    domains:
      - automation
      - weblink
      - updater

config:
python_script:
sun:
frontend:
  javascript_version:    latest
  themes:                     !include includes/themes.yaml

lovelace:
  mode:                  yaml

############################################################
#                                                          #
# Components                                               #
#                                                          #
############################################################

mqtt:
  broker:     127.0.0.1
  port:         1883

tts:
  - platform:          google
    cache:               true
    cache_dir:        /tmp/tts
    time_memory: 300
    language:        'de'

google:
  client_id:                !secret google_client
  client_secret:         !secret google_client_secret

ifttt:
  key:                   !secret ifttt_key

telegram_bot:
  - platform:            polling
    api_key:             !secret telegram_api
    allowed_chat_ids:
      - !secret chatid_1
      - !secret chatid_2

weblink:
  entities:
    - name:     Router
      url:          !secret router_ip
    - name:     Drucker
      url:          !secret printer_ip

ffmpeg:

duckdns:
  domain:                frikahome
  access_token:       !secret duckdns_token

zwave:
  usb_path:              /dev/ttyACM0
  network_key:         !secret zwave_key
  device_config:       !include zwave_device_config.yaml
  config_path:          /home/homeassistant/.homeassistant/zwave-config/

emulated_hue:

weather:
  - platform:          openweathermap
    api_key:             !secret owm_key

shell_command:
  lms_qry_alb:                    'bash /home/homeassistant/.homeassistant/shell/qry_alb.sh {{text1}} {{text2}}'
  lms_qry_alb_song:          'bash /home/homeassistant/.homeassistant/shell/qry_alb_song.sh {{text1}} {{text2}} {{text3}}'
  lms_spot_art:                  'bash /home/homeassistant/.homeassistant/shell/spot_art_top.sh {{text1}}'
  lms_spot_art_alb:           'bash /home/homeassistant/.homeassistant/shell/spot_art_alb.sh {{text1}} {{text2}}'
  lms_spot_art_alb_song: 'bash /home/homeassistant/.homeassistant/shell/spot_art_alb_song.sh {{text1}} {{text2}} {{text3}}'
  lms_spot_playlist:          'bash /home/homeassistant/.homeassistant/shell/spot_playlist.sh {{text1}}'
  fernseher_an:                'ssh -t pi@192.168.0.20 "echo on 0 | cec-client -s -d 1"'
  fernseher_aus:              'ssh -t pi@192.168.0.20 "echo standby 0 | cec-client -s -d 1"'

############################################################
#                                                          #
# Single Configs                                           #
#                                                          #
############################################################
media_player:            !include includes/media_players.yaml
device_tracker:          !include includes/device_trackers.yaml
binary_sensor:           !include includes/binary_sensor.yaml
sensor:                       !include includes/sensors.yaml
notify:                         !include includes/notify.yaml
switch:                       !include includes/switch.yaml
input_number:          !include includes/input_slider.yaml
input_select:             !include includes/input_select.yaml
input_boolean:         !include includes/input_boolean.yaml
input_text:                !include includes/input_text.yaml
scene:                       !include includes/scenes.yaml
snips:
intent_script:           !include includes/snips.yaml
light:                        !include includes/light.yaml
timer:                      !include includes/timer.yaml

############################################################
#                                                                                                                                   #
# Merged Configs                                                                                                          #
#                                                                                                                                   #
############################################################
zone:                       !include_dir_merge_list includes/zone
automation:            !include_dir_merge_list includes/automation


############################################################
#                                                                                                                                   #
# Merged Names                                                                                                          #
#                                                                                                                                   #
############################################################
group:                  !include_dir_merge_named includes/group
script:                  !include_dir_merge_named includes/scripts
