############################################################
# Binary Sensors
############################################################

- platform: workday
  country: DE
  province: NW
  workdays: [mon, tue, wed, thu, fri]
