- platform: mqtt
  state_topic: "CHANNEL/Motion/Switch"
  device_class: motion
  payload_on: "1"
  payload_off: "0"
  name: "Motion Sensor"

- platform: mqtt
  state_topic: "esp/light_office/switch"
  payload_on: "1"
  payload_off: "0"
  name: "ESP Licht Arbeitszimmer"

- platform: workday
  country: DE
  province: NW
  workdays: [mon, tue, wed, thu, fri]
