############################################################
# Home Assistant Media Players
############################################################
- platform: squeezebox
  host: 192.168.0.20

- platform: firetv

